### ISSUE TITLE
I want to be able to sign up for my BoilerRooms account using my Purdue email after accepting the Terms and Conditions Agreement

### ISSUE THREAD

**Issue by aberiggs** [aberiggs/BoilerMatch#1]
## Task List

- [x] Create a UI that has an email, password, and password confirmation field, along with a submission button.
- [x] Create a Terms and Conditions message
- [x] Implement a “show terms and conditions” visual prompt that upon clicking will open the terms and conditions and a checkbox
- [x] Create an email confirmation that confirms the account creation upon user approval
- [x] Create a serverless function to create an account given user credentials, to be fired when the users accept within the approval email

## Implementation Ideas/Details

- Send an email when an account is successfully verified
