### ISSUE TITLE
I want to be prompted to make a secure password, and give an option for my password to be hidden as I type it out

### ISSUE THREAD

**Issue by aberiggs** [aberiggs/BoilerMatch#2]
## Task List

- [x] Design a function that only accepts passwords that are of acceptable criteria
- [x] Build and modify any UI to add error messages and restrictions on account creation attempts based on password input
- [x] Build and modify UI to add a means of hiding/showing the password (across login and registration pages)

## Implementation Ideas/Details
