### ISSUE TITLE
I want to be able to add a profile picture

### ISSUE THREAD

**Issue by aberiggs** [aberiggs/BoilerMatch#3]
## Task List

- [x] Create a UI for being able to add photos for user profile picture
- [x] Send to backend and store in Azure blob, while updating URL to photo in database
- [x] Connect UI for displaying profile photo
- [x] Test to ensure that the backend processed the image request

## Implementation Ideas/Details
