### ISSUE TITLE
I want to be able to edit and change my information and preferences on my profile after I originally put it in

### ISSUE THREAD

**Issue by aberiggs** [aberiggs/BoilerMatch#4]
## Task List

- [ ] Load previous information for the unique user from the database to the backend 
- [ ] Display previous information on the UI
- [ ] Update information on UI to what the user submits (create UI and retrieve information from database)
- [ ] Store new information for the unique user to database 

## Implementation Ideas/Details
