### ISSUE TITLE
I want to be able to specify my preferences (preferred gender, bed time, noise level, cleanliness, welcoming of guests)

### ISSUE THREAD

**Issue by azajzon** [aberiggs/BoilerMatch#5]
## Task List

- [ ] Research React Native to learn how to create UI
- [ ] Create UI to input, save and display preferences
- [ ] Connect user class with UI
- [ ] Store preferences for the unique user to database
- [ ] Test to ensure that information shows up on user profile after it is entered

## Implementation Ideas/Details
